
joints:
  forearm_roll:
    effort: 0.75
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: False
  wrist_pitch:
    effort: 0.75
    gradual_startup_position: 0
    gradual_startup_time: 1.0
    antagonist: True
